name: Require Labels
on:
  issues:
    types: [opened]
jobs:
  label:
    name: Check issue labels
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: minimum
          count: 1
          labels: "+P1, +P2, +P3"
